# Generated by Django 2.1.5 on 2019-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20190202_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
