# Generated by Django 2.1.5 on 2019-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_important',
            field=models.BooleanField(default=False),
        ),
    ]
