# Generated by Django 2.1.7 on 2019-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20190223_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Kategoria'),
        ),
    ]
